R=[
dict(no=44,q=r"그림과 같이 선분 $\mathrm{AB}$를 지름으로 하는 반원의 호 $\mathrm{AB}$ 위에 두 점 $\mathrm{C}$, $\mathrm{D}$가 있다. 선분 $\mathrm{AB}$의 중점 $\mathrm{O}$에 대하여 두 선분 $\mathrm{AD}$, $\mathrm{CO}$가 점 $\mathrm{E}$에서 만나고, $\overline{\mathrm{CE}}=4$, $\overline{\mathrm{ED}}=3\sqrt2$, $\angle\mathrm{CEA}=\dfrac34\pi$이다. $\overline{\mathrm{AC}}\times\overline{\mathrm{CD}}$의 값은?",
 cond=None,ch=[r"6\sqrt{10}",r"10\sqrt5",r"16\sqrt2",r"12\sqrt5",r"20\sqrt2"],ans="5",fig="지름 AB인 반원, 호 위의 C, D, 중심 O, AD와 CO의 교점 E, $\angle$CEA$=\frac34\pi$",
 th="12",lk=[],
 fj=r"삼각형 $\mathrm{CDE}$는 두 변과 끼인각($\frac\pi4$)이 주어져 결정되므로 $\overline{\mathrm{CD}}$부터 구하고, $\overline{\mathrm{AC}}$는 외접원·이등변삼각형 $\mathrm{AOC}$로 구한다.",
 bh="문제해결",rs=["그래프·도형 해석","미지수 소거·연립"],st=["S07","S08"],
 sol=r"$\overline{\mathrm{CD}}^2=16+18-2\cdot4\cdot3\sqrt2\cdot\frac1{\sqrt2}=10$. $\cos\angle\mathrm{CDE}=\frac1{\sqrt5}$, $\sin=\frac2{\sqrt5}$. $\overline{\mathrm{AC}}=x$, $\overline{\mathrm{AE}}=y$: $x^2=y^2+4\sqrt2y+16$ ㉠; $2R=\frac{\sqrt5}2x$, $\cos\alpha=\frac2{\sqrt5}$, $\sin\alpha=\frac{\sqrt5}5$; 삼각형 ACE 사인법칙 $\sqrt2x=\sqrt5y$ ㉡ → $3y^2-8\sqrt2y-32=0$, $y=4\sqrt2$, $x=4\sqrt5$. $\overline{\mathrm{AC}}\cdot\overline{\mathrm{CD}}=4\sqrt5\cdot\sqrt{10}=20\sqrt2$"),
dict(no=45,q=r"그림과 같이 $\overline{\mathrm{AB}}=2$, $\overline{\mathrm{AD}}=1$, $\angle\mathrm{DAB}=\dfrac23\pi$, $\angle\mathrm{BCD}=\dfrac34\pi$인 사각형 $\mathrm{ABCD}$가 있다. 삼각형 $\mathrm{BCD}$의 외접원의 반지름의 길이를 $R_1$, 삼각형 $\mathrm{ABD}$의 외접원의 반지름의 길이를 $R_2$라 하자. 다음은 $R_1\times R_2$의 값을 구하는 과정이다. 위의 (가), (나), (다)에 알맞은 수를 각각 $p,q,r$이라 할 때, $9\times(p\times q\times r)^2$의 값을 구하시오.",
 cond=r"삼각형 $\mathrm{BCD}$에서 사인법칙에 의하여 $R_1=\dfrac{\sqrt2}2\times\overline{\mathrm{BD}}$. 삼각형 $\mathrm{ABD}$에서 사인법칙에 의하여 $R_2=$ (가) $\times\overline{\mathrm{BD}}$. 삼각형 $\mathrm{ABD}$에서 코사인법칙에 의하여 $\overline{\mathrm{BD}}^2=2^2+1^2-($(나)$)$이므로 $R_1\times R_2=$ (다)",
 ch=None,ans="98",fig="사각형 ABCD와 삼각형 BCD, ABD의 외접원(반지름 $R_1$, $R_2$)",
 th="12",lk=[],
 fj=r"두 외접원 모두 공통변 $\overline{\mathrm{BD}}$에 대한 사인법칙으로 쓰고, $\overline{\mathrm{BD}}^2$는 코사인법칙으로 구한다.",
 bh="이해",rs=["그래프·도형 해석"],st=["S07","S08"],
 sol=r"$R_2=\frac{\overline{\mathrm{BD}}}{2\sin\frac23\pi}=\frac{\sqrt3}3\overline{\mathrm{BD}}$ (가). $\overline{\mathrm{BD}}^2=4+1-2\cdot2\cdot1\cdot\cos\frac23\pi=5-(-2)=7$ (나)$=-2$. $R_1R_2=\frac{\sqrt6}6\cdot7=\frac{7\sqrt6}6$ (다). $9(pqr)^2=9\left(\frac{\sqrt3}3\cdot(-2)\cdot\frac{7\sqrt6}6\right)^2=98$"),
dict(no=46,q=r"반지름의 길이가 $2\sqrt7$인 원에 내접하고 $\angle\mathrm{A}=\dfrac\pi3$인 삼각형 $\mathrm{ABC}$가 있다. 점 $\mathrm{A}$를 포함하지 않는 호 $\mathrm{BC}$ 위의 점 $\mathrm{D}$에 대하여 $\sin(\angle\mathrm{BCD})=\dfrac{2\sqrt7}7$일 때, $\overline{\mathrm{BD}}+\overline{\mathrm{CD}}$의 값은?",
 cond=None,ch=[r"\frac{19}2","10",r"\frac{21}2","11",r"\frac{23}2"],ans="2",fig="원에 내접하는 삼각형 ABC($\angle$A$=\frac\pi3$)와 호 BC 위의 점 D",
 th="12",lk=[],
 fj=r"같은 외접원을 공유하므로 사인법칙으로 $\overline{\mathrm{BC}}$, $\overline{\mathrm{BD}}$를 구하고, 내접사각형 대각의 합 $\pi$로 $\angle\mathrm{BDC}=\frac23\pi$를 얻는다.",
 bh="계산",rs=["그래프·도형 해석"],st=["S07","S08"],
 sol=r"$\overline{\mathrm{BC}}=4\sqrt7\sin\frac\pi3=2\sqrt{21}$, $\overline{\mathrm{BD}}=4\sqrt7\cdot\frac{2\sqrt7}7=8$. $\angle\mathrm{BDC}=\frac23\pi$: $84=x^2+64+8x$ → $x=2$. 합 $10$"),
dict(no=47,q=r"$\angle\mathrm{A}>\dfrac\pi2$인 삼각형 $\mathrm{ABC}$의 꼭짓점 $\mathrm{A}$에서 선분 $\mathrm{BC}$에 내린 수선의 발을 $\mathrm{H}$라 하자. $\overline{\mathrm{AB}}:\overline{\mathrm{AC}}=\sqrt2:1$, $\overline{\mathrm{AH}}=2$이고, 삼각형 $\mathrm{ABC}$의 외접원의 넓이가 $50\pi$일 때, 선분 $\mathrm{BH}$의 길이는?",
 cond=None,ch=["6",r"\frac{25}4",r"\frac{13}2",r"\frac{27}4","7"],ans="1",fig=None,th="12",lk=[],
 fj=r"$\sin C=\frac{\overline{\mathrm{AH}}}{\overline{\mathrm{AC}}}$와 사인법칙 $\overline{\mathrm{AB}}=2R\sin C$를 연결한다.",
 bh="계산",rs=["그래프·도형 해석","미지수 소거·연립"],st=["S07"],
 sol=r"$R=5\sqrt2$. $\overline{\mathrm{AC}}=x$, $\overline{\mathrm{AB}}=\sqrt2x$, $\sin C=\frac2x$. $\sqrt2x=2\cdot5\sqrt2\cdot\frac2x$ → $x^2=20$, $\overline{\mathrm{AB}}=2\sqrt{10}$. $\overline{\mathrm{BH}}=\sqrt{40-4}=6$"),
]
