R=[
dict(no=10,q=r"그림과 같이 곡선 $y=1-2^{-x}$ 위의 제1사분면에 있는 점 $\mathrm{A}$를 지나고 $y$축에 평행한 직선이 곡선 $y=2^x$과 만나는 점을 $\mathrm{B}$라 하자. 점 $\mathrm{A}$를 지나고 $x$축에 평행한 직선이 곡선 $y=2^x$과 만나는 점을 $\mathrm{C}$, 점 $\mathrm{C}$를 지나고 $y$축에 평행한 직선이 곡선 $y=1-2^{-x}$과 만나는 점을 $\mathrm{D}$라 하자. $\overline{\mathrm{AB}}=2\overline{\mathrm{CD}}$일 때, 사각형 $\mathrm{ABCD}$의 넓이는?",
 cond=None,ch=[r"\frac52\log_2 3-\frac54",r"3\log_2 3-\frac32",r"\frac72\log_2 3-\frac74",r"4\log_2 3-2",r"\frac92\log_2 3-\frac94"],ans="3",
 fig="곡선 $y=2^x$, $y=1-2^{-x}$와 점 A(제1사분면, 아래 곡선 위), B(A 위쪽 $y=2^x$ 위), C(A와 같은 높이, $y=2^x$ 위), D(C 아래 $y=1-2^{-x}$ 위); 사각형 ABCD가 색칠됨",
 th="03",lk=["06"],
 fj=r"A의 $x$좌표 $a$, C의 $x$좌표 $c$로 두고 'A, C의 $y$좌표가 같다'는 관계로 미지수를 하나로 줄인다.",
 bh="추론",rs=["그래프·도형 해석","미지수 소거·연립","치환·보조함수 도입"],st=["S05"],
 sol=r"$\overline{\mathrm{AB}}=2^a+2^{-a}-1$, $\overline{\mathrm{CD}}=2^c+2^{-c}-1$, $2^c=1-2^{-a}$. $2^a=t$로 두면 $t+\frac1t-1=-\frac2t+\frac{2t}{t-1}$ → $(t-3)(t^2-t+1)=0$, $t=3$. $a=\log_2 3$, $c=1-\log_2 3$. 넓이 $\frac12(a-c)(2^a-1+2^{-c})=\frac12(2\log_2 3-1)\left(3-1+\frac32\right)=\frac72\log_2 3-\frac74$"),
dict(no=11,q=r"두 자연수 $a,b$에 대하여 함수 $f(x)=\begin{cases}2^{x+a}+b & (x\le-8)\\ -3^{x-3}+8 & (x>-8)\end{cases}$이 다음 조건을 만족시킬 때, $a+b$의 값은?",
 cond=r"집합 $\{f(x)\mid x\le k\}$의 원소 중 정수인 것의 개수가 $2$가 되도록 하는 모든 실수 $k$의 값의 범위는 $3\le k<4$이다.",
 ch=["11","13","15","17","19"],ans="2",fig=None,th="03",lk=["07"],
 fj=r"$x>-8$ 부분에서 $3\le k<4$일 때 나오는 정수값이 $6,7$뿐이므로, $x\le-8$ 부분이 새 정수를 만들지 않도록 치역을 제한한다.",
 bh="문제해결",rs=["그래프·도형 해석","정수 조건으로 후보 좁히기"],st=["S05"],
 sol=r"$x>-8$에서 $3\le k<4$이면 정수 $f(x)=6,7$ ($f(3)=7$, $f(4)=5$). 따라서 $x\le-8$ 부분의 정수값은 $6$뿐 → $b=5$, $6\le f(-8)=2^{-8+a}+5<7$ → $8\le a<9$, $a=8$. $a+b=13$"),
dict(no=12,q=r"$k>1$인 실수 $k$에 대하여 두 곡선 $y=2^x+\dfrac k2$, $y=k\cdot\left(\dfrac12\right)^x+k-2$가 만나는 점을 $\mathrm{A}$라 하고, 점 $\mathrm{A}$를 지나고 기울기가 $-1$인 직선이 곡선 $y=2^{x-2}-3$과 만나는 점을 $\mathrm{B}$라 하자. 삼각형 $\mathrm{AOB}$의 넓이가 $16$일 때, $k+\log_2 k=\dfrac qp$이다. $p+q$의 값을 구하시오. (단, $\mathrm{O}$는 원점이고, $p$와 $q$는 서로소인 자연수이다.)",
 cond=None,ch=None,ans="38",fig=None,th="03",lk=["07"],
 fj=r"교점 $\mathrm A$가 $\left(\log_2\frac k2,k\right)$로 정리되어 곡선 $y=2^{x+1}$ 위를 움직이고, $y=2^{x-2}-3$은 이 곡선의 평행이동이므로 $\overline{\mathrm{AB}}$가 상수가 된다.",
 bh="문제해결",rs=["그래프·도형 해석","치환·보조함수 도입"],st=["S05"],
 sol=r"$2^a=t$: $t+\frac k2=\frac kt+k-2\Rightarrow(t+2)(2t-k)=0$, $t=\frac k2$. $\mathrm A\left(\log_2\frac k2,k\right)$는 $y=2^{x+1}$ 위. $y=2^{x-2}-3$은 이를 $(3,-3)$ 평행이동 → $\mathrm B\left(\log_2\frac k2+3,k-3\right)$, $\overline{\mathrm{AB}}=3\sqrt2$. 높이 $h=\frac{16\sqrt2}{3}$. 직선 $x+y-k-\log_2\frac k2=0$과 원점 거리: $\frac{|k+\log_2 k-1|}{\sqrt2}=\frac{16\sqrt2}3$ → $k+\log_2k=\frac{35}{3}$. $p+q=38$"),
dict(no=13,q=r"그림과 같이 곡선 $y=2^x$ 위에 두 점 $\mathrm{P}(a,2^a)$, $\mathrm{Q}(b,2^b)$이 있다. 직선 $\mathrm{PQ}$의 기울기를 $m$이라 할 때, 점 $\mathrm{P}$를 지나며 기울기가 $-m$인 직선이 $x$축, $y$축과 만나는 점을 각각 $\mathrm{A}$, $\mathrm{B}$라 하고, 점 $\mathrm{Q}$를 지나며 기울기가 $-m$인 직선이 $x$축과 만나는 점을 $\mathrm{C}$라 하자. $\overline{\mathrm{AB}}=4\overline{\mathrm{PB}}$, $\overline{\mathrm{CQ}}=3\overline{\mathrm{AB}}$일 때, $90(a+b)$의 값을 구하시오. (단, $0<a<b$)",
 cond=None,ch=None,ans="220",
 fig="곡선 $y=2^x$ 위의 P, Q와 기울기 $-m$인 평행한 두 직선(P를 지나 $y$축의 B, $x$축의 A와 만남 / Q를 지나 $x$축의 C와 만남)",
 th="03",lk=[],
 fj=r"두 직선이 평행하므로 닮은 삼각형으로 길이비를 높이비($2^a:2^b$)로 옮긴다.",
 bh="추론",rs=["그래프·도형 해석","미지수 소거·연립"],st=["S05"],
 sol=r"$\overline{\mathrm{PB}}=k$면 $\overline{\mathrm{AP}}=3k$, $\overline{\mathrm{CQ}}=12k$, 닮음으로 $2^a:2^b=1:4$ → $b=a+2$, $m=\frac{2^{a+2}-2^a}{2}=3\cdot2^{a-1}$. A의 $x$좌표 $a+\frac23$. $\overline{\mathrm{AO}}:\overline{\mathrm{DO}}=4:1$ → $a+\frac23=4a$, $a=\frac29$, $b=\frac{20}9$. $90(a+b)=220$"),
]
