R=[
dict(no=21,q=r"자연수 $n$에 대하여 곡선 $y=2^x$ 위의 두 점 $\mathrm{A}_n$, $\mathrm{B}_n$이 다음 조건을 만족시킨다. 중심이 직선 $y=x$ 위에 있고 두 점 $\mathrm{A}_n$, $\mathrm{B}_n$을 지나는 원이 곡선 $y=\log_2 x$와 만나는 두 점의 $x$좌표 중 큰 값을 $x_n$이라 하자. $x_1+x_2+x_3$의 값은?",
 cond=r"(가) 직선 $\mathrm{A}_n\mathrm{B}_n$의 기울기는 $3$이다.\\(나) $\overline{\mathrm{A}_n\mathrm{B}_n}=\sqrt{10}\,n$",
 ch=[r"\frac{150}7",r"\frac{155}7",r"\frac{160}7",r"\frac{165}7",r"\frac{170}7"],ans="5",fig=None,th="06",lk=["03"],
 fj=r"원의 중심이 $y=x$ 위이므로 원과 두 곡선이 모두 $y=x$ 대칭 → $x_n$은 $\mathrm B_n$의 $y$좌표와 같다.",
 bh="추론",rs=["대칭성·주기성 활용","미지수 소거·연립"],st=["S05"],
 sol=r"$\mathrm A_n(a_n,2^{a_n})$, $\mathrm B_n(b_n,2^{b_n})$. (가) $2^{b_n}-2^{a_n}=3(b_n-a_n)$, (나) 대입 → $b_n-a_n=n$. $2^{b_n}(1-2^{-n})=3n$ → $2^{b_n}=\frac{3n\cdot2^n}{2^n-1}$. $x_n=2^{b_n}$이므로 $x_1+x_2+x_3=6+8+\frac{72}7=\frac{170}7$"),
dict(no=22,q=r"$a>1$인 실수 $a$에 대하여 직선 $y=-x+4$가 두 곡선 $y=a^{x-1}$, $y=\log_a(x-1)$과 만나는 점을 각각 $\mathrm{A}$, $\mathrm{B}$라 하고, 곡선 $y=a^{x-1}$이 $y$축과 만나는 점을 $\mathrm{C}$라 하자. $\overline{\mathrm{AB}}=2\sqrt2$일 때, 삼각형 $\mathrm{ABC}$의 넓이는 $S$이다. $50S$의 값을 구하시오.",
 cond=None,ch=None,ans="192",fig="곡선 $y=a^{x-1}$, $y=\log_a(x-1)$과 직선 $y=-x+4$가 각각 A, B에서 만나고, C는 $y=a^{x-1}$의 $y$절편; 삼각형 ABC 색칠",
 th="06",lk=["07"],
 fj=r"두 곡선은 직선 $y=x-1$에 대하여 대칭이므로 $\mathrm{AB}$의 중점은 $y=-x+4$와 $y=x-1$의 교점 $\mathrm M\left(\frac52,\frac32\right)$이다.",
 bh="추론",rs=["대칭성·주기성 활용","그래프·도형 해석"],st=["S05"],
 sol=r"$\mathrm M\left(\frac52,\frac32\right)$, $\overline{\mathrm{AM}}=\sqrt2$ → $\mathrm A\left(\frac32,\frac52\right)$, $a^{1/2}=\frac52$, $a=\frac{25}4$. $\mathrm C\left(0,\frac4{25}\right)$. $\overline{\mathrm{CH}}=\frac{|4/25-4|}{\sqrt2}=\frac{48\sqrt2}{25}$. $S=\frac12\cdot2\sqrt2\cdot\frac{48\sqrt2}{25}=\frac{96}{25}$, $50S=192$"),
dict(no=23,q=r"자연수 $n$에 대하여 함수 $f(x)$를 $f(x)=\begin{cases}|3^{x+2}-n| & (x<0)\\ |\log_2(x+4)-n| & (x\ge0)\end{cases}$이라 하자. 실수 $t$에 대하여 $x$에 대한 방정식 $f(x)=t$의 서로 다른 실근의 개수를 $g(t)$라 할 때, 함수 $g(t)$의 최댓값이 $4$가 되도록 하는 모든 자연수 $n$의 값의 합을 구하시오.",
 cond=None,ch=None,ans="33",fig=None,th="07",lk=["03","04"],
 fj=r"각 부분을 평행이동 + 절댓값으로 그리고, $x=0$에서의 값 $|9-n|$, $|2-n|$의 부호로 $n$을 구간별로 나눈다.",
 bh="문제해결",rs=["그래프·도형 해석","경우 나누기"],st=["S05"],
 sol=r"$x<0$: $y=|3^{x+2}-n|$은 점근선 $y=n$, $(0,|9-n|)$. $x\ge0$: $y=|\log_2(x+4)-n|$은 $(0,|2-n|)$. $g(t)$ 최댓값 4가 되려면 두 부분 모두 꺾임이 생겨야 하므로 $9-n>0$, $2-n<0$ → $n=3,\dots,8$. 합 $33$"),
dict(no=24,q=r"직선 $y=2x+k$가 두 함수 $y=\left(\dfrac23\right)^{x+3}+1$, $y=\left(\dfrac23\right)^{x+1}+\dfrac83$의 그래프와 만나는 점을 각각 $\mathrm{P}$, $\mathrm{Q}$라 하자. $\overline{\mathrm{PQ}}=\sqrt5$일 때, 상수 $k$의 값은?",
 cond=None,ch=[r"\frac{31}6",r"\frac{16}3",r"\frac{11}2",r"\frac{17}3",r"\frac{35}6"],ans="4",fig="직선 $y=2x+k$와 두 감소 지수곡선; 아래 곡선 위의 P, 위 곡선 위의 Q",
 th="05",lk=["03"],
 fj=r"기울기가 $2$이므로 $\overline{\mathrm{PQ}}=\sqrt5$에서 $x$좌표 차가 $1$임을 바로 얻고, 두 점을 $p$ 하나로 표현한다.",
 bh="계산",rs=["미지수 소거·연립"],st=["S03","S04"],
 sol=r"$\mathrm P(p,2p+k)$, $\mathrm Q(p+1,2p+k+2)$. $\left(\frac23\right)^{p+3}+1=2p+k$, $\left(\frac23\right)^{p+2}+\frac83=2p+k+2$ → $\left(\frac23\right)^{p+2}=1$, $p=-2$. $k=\frac23+1+4=\frac{17}3$"),
dict(no=25,q=r"다음 조건을 만족시키는 모든 자연수 $k$의 값의 합은?",
 cond=r"$\log_2\sqrt{-n^2+10n+75}-\log_4(75-kn)$의 값이 양수가 되도록 하는 자연수 $n$의 개수가 $12$이다.",
 ch=["6","7","8","9","10"],ans="4",fig=None,th="05",lk=["02"],
 fj=r"진수 조건 두 개와 부등식을 모두 $n$의 범위로 바꾼 뒤, 세 범위의 교집합 크기를 $k$별로 센다.",
 bh="추론",rs=["조건의 식 번역","경우 나누기","정수 조건으로 후보 좁히기"],st=["S03","S04"],
 sol=r"진수: $1\le n<15$ ㉠, $n<\frac{75}k$ ㉡. 부등식 $\log_4(-n^2+10n+75)>\log_4(75-kn)$ → $n(n-10-k)<0$ → $n<10+k$ ㉢. 개수 12 → $k>2$. $k=3$: $1\le n<13$ (12개, 적합), $k=4$: 13개, $k=5$: 14개, $k=6$: $n<\frac{25}2$ (12개, 적합), $k\ge7$: $\frac{75}k<11$ 부적합. 합 $3+6=9$"),
dict(no=26,q=r"두 양수 $a,b$에 대하여 곡선 $y=a\sin b\pi x\left(0\le x\le\dfrac3b\right)$이 직선 $y=a$와 만나는 서로 다른 두 점을 $\mathrm{A}$, $\mathrm{B}$라 하자. 삼각형 $\mathrm{OAB}$의 넓이가 $5$이고 직선 $\mathrm{OA}$의 기울기와 직선 $\mathrm{OB}$의 기울기의 곱이 $\dfrac54$일 때, $a+b$의 값은? (단, $\mathrm{O}$는 원점이다.)",
 cond=None,ch=["1","2","3","4","5"],ans="3",fig="곡선 $y=a\sin b\pi x$가 직선 $y=a$와 A, B(최댓점 두 곳)에서 만나고 삼각형 OAB 색칠",
 th="09",lk=[],
 fj=r"주기 $\frac2b$로 최댓점 $\mathrm A\left(\frac1{2b},a\right)$, $\mathrm B\left(\frac5{2b},a\right)$를 바로 적는다.",
 bh="계산",rs=["대칭성·주기성 활용","미지수 소거·연립"],st=["S06"],
 sol=r"넓이 $\frac12\cdot a\cdot\frac2b=5\Rightarrow a=5b$. 기울기 곱 $2ab\cdot\frac{2ab}5=\frac54\Rightarrow ab=\frac54$. $a=\frac52$, $b=\frac12$, $a+b=3$"),
dict(no=27,q=r"$5$ 이하의 두 자연수 $a,b$에 대하여 열린구간 $(0,2\pi)$에서 정의된 함수 $y=a\sin x+b$의 그래프가 직선 $x=\pi$와 만나는 점의 집합을 $A$라 하고, 두 직선 $y=1$, $y=3$과 만나는 점의 집합을 각각 $B$, $C$라 하자. $n(A\cup B\cup C)=3$이 되도록 하는 $a,b$의 순서쌍 $(a,b)$에 대하여 $a+b$의 최댓값을 $M$, 최솟값을 $m$이라 할 때, $Mm$의 값을 구하시오.",
 cond=None,ch=None,ans="24",fig=None,th="09",lk=["10"],
 fj=r"$x=\pi$와의 교점 $(\pi,b)$는 항상 1개이므로, $b$ 값(1~5)별로 $y=1$, $y=3$과의 교점 수를 그래프로 센다.",
 bh="추론",rs=["경우 나누기","그래프·도형 해석"],st=["S06"],
 sol=r"(i) $b=1$: $a>2$ → $(3,1),(4,1),(5,1)$. (ii) $b=2$: $a=1$ → $(1,2)$. (iii) $b=3$: $-a+3<1$, $a>2$ → $(3,3),(4,3),(5,3)$. (iv) $b=4$: $1<-a+4<3$ → $(2,4)$. (v) $b=5$: $2<a<4$ → $(3,5)$. $M=8$, $m=3$, $Mm=24$"),
]
