R=[
dict(no=1,q=r"함수 $f(x)=-(x-2)^2+k$에 대하여 다음 조건을 만족시키는 자연수 $n$의 개수가 $2$일 때, 상수 $k$의 값은?",
 cond=r"$\sqrt{3}^{\,f(n)}$의 네제곱근 중 실수인 것을 모두 곱한 값이 $-9$이다.",
 ch=["8","9","10","11","12"],ans="2",fig=None,th="01",lk=["02"],
 fj=r"양수의 네제곱근 중 실수는 $\pm$ 두 개이므로 그 곱은 $-\sqrt{3}^{\,f(n)/2}$이고, 이것이 $-9$가 되는 $f(n)$ 값을 먼저 구한다.",
 bh="추론",rs=["조건의 식 번역","대칭성·주기성 활용"],st=["S01","S02"],
 sol=r"$\sqrt[4]{\sqrt3^{f(n)}}\cdot\left(-\sqrt[4]{\sqrt3^{f(n)}}\right)=-3^{\frac14 f(n)}=-9\Rightarrow f(n)=8$. 대칭축 $x=2$이므로 $f(n)=8$인 자연수 $n$이 2개이려면 그래프가 $(1,8)$을 지나야 한다. $f(1)=-1+k=8\therefore k=9$"),
dict(no=2,q=r"다음 조건을 만족시키는 최고차항의 계수가 $1$인 이차함수 $f(x)$가 존재하도록 하는 모든 자연수 $n$의 값의 합을 구하시오.",
 cond=r"(가) $x$에 대한 방정식 $(x^n-64)f(x)=0$은 서로 다른 두 실근을 갖고, 각각의 실근은 중근이다.\\(나) 함수 $f(x)$의 최솟값은 음의 정수이다.",
 ch=None,ans="24",fig=None,th="01",lk=[],
 fj=r"$x^n=64$의 실근 개수가 $n$의 홀짝에 따라 달라지므로 $n$을 홀수·짝수로 나눈다.",
 bh="추론",rs=["경우 나누기","정수 조건으로 후보 좁히기"],st=["S01","S02"],
 sol=r"$f$의 최솟값이 음수이므로 $f(x)=0$은 서로 다른 두 실근을 가진다. (i) $n$ 홀수: $x^n=64$의 실근 1개 → 모든 근이 중근일 수 없다. (ii) $n$ 짝수: $x=\pm2^{6/n}$이므로 $f(x)=(x-2^{6/n})(x+2^{6/n})$, 최솟값 $f(0)=-2^{12/n}$이 음의 정수 → $n=2,4,6,12$. 합 $24$"),
dict(no=3,q=r"자연수 $n$에 대하여 $4\log_{64}\left(\dfrac{3}{4n+16}\right)$의 값이 정수가 되도록 하는 $1000$ 이하의 모든 $n$의 값의 합을 구하시오.",
 cond=None,ch=None,ans="426",fig=None,th="02",lk=["05"],
 fj=r"식을 $\log_8\left(\frac{3}{4n+16}\right)^2$로 정리하고, 값 자체를 정수 $m$으로 두어 $n$이 아니라 $m$(또는 $k$) 기준으로 센다.",
 bh="추론",rs=["조건의 식 번역","정수 조건으로 후보 좁히기"],st=["S03","S04"],
 sol=r"$4\log_{64}\frac{3}{4n+16}=\log_8\left(\frac{3}{4n+16}\right)^2$이 정수 $m$ → $\left(\frac{3}{4n+16}\right)^2=8^m$. $4n+16$이 3의 배수여야 하므로 $n=3k-1$ ($1\le k\le333$). $\left(\frac{1}{4k+4}\right)^2=2^{3m}\Rightarrow (k+1)^2=2^{-3m-4}$, 즉 $2^2,2^8,2^{14}$ → $k=1,15,127$, $n=2,44,380$. 합 $426$"),
dict(no=4,q=r"수직선 위의 두 점 $\mathrm{P}(\log_5 3)$, $\mathrm{Q}(\log_5 12)$에 대하여 선분 $\mathrm{PQ}$를 $m:(1-m)$으로 내분하는 점의 좌표가 $1$일 때, $4^m$의 값은? (단, $m$은 $0<m<1$인 상수이다.)",
 cond=None,ch=[r"\frac{7}{6}",r"\frac{4}{3}",r"\frac{3}{2}",r"\frac{5}{3}",r"\frac{11}{6}"],ans="4",fig=None,th="02",lk=[],
 fj=r"내분점 공식으로 식을 세우면 $m$에 대한 일차방정식이 되고, $m$이 로그 꼴로 나온다.",
 bh="계산",rs=["조건의 식 번역"],st=["S03"],
 sol=r"$m\log_5 12+(1-m)\log_5 3=1\Rightarrow m\log_5 4=\log_5\frac53\Rightarrow m=\log_4\frac53$, $4^m=\frac53$"),
dict(no=5,q=r"두 양수 $a,b$가 $\log_9 a+\log_3 b=2$, $\log_3 a=8\log_9 b$를 만족시킬 때, $\dfrac{a}{b}$의 값은?",
 cond=None,ch=["1","3","9","27","81"],ans="3",fig=None,th="02",lk=[],
 fj=r"밑을 $3$으로 통일하여 $\log_3 a$, $\log_3 b$에 대한 연립일차방정식으로 본다.",
 bh="계산",rs=["미지수 소거·연립"],st=["S03"],
 sol=r"$\frac12\log_3a+\log_3b=2$, $\log_3a=4\log_3b$ → $\log_3b=\frac23$, $\log_3a=\frac83$. $\log_3\frac ab=2$, $\frac ab=9$"),
dict(no=6,q=r"두 상수 $a,b$ $(1<a<b)$에 대하여 좌표평면 위의 두 점 $(a,\log_2 a)$, $(b,\log_2 b)$를 지나는 직선의 $y$절편과 두 점 $(a,\log_4 a)$, $(b,\log_4 b)$를 지나는 직선의 $y$절편이 같다. 함수 $f(x)=a^{bx}+b^{ax}$에 대하여 $f(1)=40$일 때, $f(2)$의 값은?",
 cond=None,ch=["760","800","840","880","920"],ans="2",fig=None,th="02",lk=["04"],
 fj=r"$\log_4=\frac12\log_2$이므로 두 $y$절편 식을 $\log_2$로 통일해 같다고 놓으면 $a^b=b^a$가 나온다.",
 bh="추론",rs=["조건의 식 번역","미지수 소거·연립"],st=["S03"],
 sol=r"$y$절편: $-\frac{a(\log_2b-\log_2a)}{b-a}+\log_2a=-\frac12\cdot\frac{a(\log_2b-\log_2a)}{b-a}+\frac12\log_2a$ → $(b-a)\log_2a=a\log_2\frac ba$ → $a^b=b^a$. $f(1)=a^b+b^a=40\Rightarrow a^b=b^a=20$. $f(2)=(a^b)^2+(b^a)^2=800$"),
dict(no=7,q=r"상수 $a$ $(a>1)$과 양수 $t$에 대하여 곡선 $y=a^x$과 두 직선 $x=t$, $x=2t$가 만나는 점을 각각 $\mathrm{A}$, $\mathrm{B}$라 하고, 점 $\mathrm{B}$에서 $x$축에 내린 수선의 발을 $\mathrm{C}$라 하자. $\overline{\mathrm{AB}}=\overline{\mathrm{AC}}$이고 삼각형 $\mathrm{ACB}$의 넓이가 $8$일 때, $at$의 값은?",
 cond=None,ch=[r"2^{\frac94}",r"2^{\frac{23}{8}}",r"2^{\frac72}",r"2^{\frac{33}{8}}",r"2^{\frac{19}{4}}"],ans="1",fig=None,th="03",lk=[],
 fj=r"이등변삼각형이므로 $\mathrm{A}$에서 $\mathrm{BC}$에 내린 수선의 발이 $\mathrm{BC}$의 중점이다 → $2a^t=a^{2t}$.",
 bh="추론",rs=["그래프·도형 해석","미지수 소거·연립"],st=["S05"],
 sol=r"$\mathrm A(t,a^t)$, $\mathrm B(2t,a^{2t})$, $\mathrm C(2t,0)$. $\mathrm{BC}$의 중점 높이 $=a^t$ → $2a^t=a^{2t}$, $a^t=2$. 넓이 $\frac12\cdot t\cdot a^{2t}=8\Rightarrow t=4$, $a=2^{1/4}$, $at=2^{9/4}$"),
dict(no=8,q=r"상수 $a$ $(a>1)$에 대하여 곡선 $y=a^x-2$ 위의 점 중 제1사분면에 있는 점 $\mathrm{A}$를 지나고 $y$축에 평행한 직선이 $x$축과 만나는 점을 $\mathrm{B}$, 곡선 $y=a^x-2$의 점근선과 만나는 점을 $\mathrm{C}$라 하자. $\overline{\mathrm{AB}}=\overline{\mathrm{BC}}$이고 삼각형 $\mathrm{AOC}$의 넓이가 $8$일 때, $a\times\overline{\mathrm{OB}}$의 값은? (단, $\mathrm{O}$는 원점이다.)",
 cond=None,ch=[r"2^{\frac{13}{6}}",r"2^{\frac73}",r"2^{\frac52}",r"2^{\frac83}",r"2^{\frac{17}{6}}"],ans="3",fig=None,th="03",lk=[],
 fj=r"점근선 $y=-2$이므로 $\overline{\mathrm{BC}}=2$, 따라서 $\mathrm A$의 $y$좌표가 $2$로 바로 정해진다.",
 bh="추론",rs=["그래프·도형 해석"],st=["S05"],
 sol=r"$\overline{\mathrm{BC}}=2=\overline{\mathrm{AB}}$ → $\mathrm A(p,2)$, $a^p=4$. 넓이 $\frac12\cdot4\cdot\overline{\mathrm{OB}}=8\Rightarrow\overline{\mathrm{OB}}=4$, $a^4=4$, $a=\sqrt2$. $a\cdot\overline{\mathrm{OB}}=4\sqrt2=2^{5/2}$"),
dict(no=9,q=r"곡선 $y=\left(\dfrac15\right)^{x-3}$과 직선 $y=x$가 만나는 점의 $x$좌표를 $k$라 하자. 실수 전체의 집합에서 정의된 함수 $f(x)$가 다음 조건을 만족시킨다. $f\left(\dfrac{1}{k^3\times5^{3k}}\right)$의 값을 구하시오.",
 cond=r"$x>k$인 모든 실수 $x$에 대하여 $f(x)=\left(\dfrac15\right)^{x-3}$이고 $f(f(x))=3x$이다.",
 ch=None,ans="36",fig=None,th="03",lk=[],
 fj=r"$k$의 정의 $\left(\frac15\right)^{k-3}=k$에서 $k\cdot5^k=5^3$을 얻어 입력값을 $\frac1{5^9}$로 단순화하고, 이것을 $f(\alpha)$ 꼴로 본다.",
 bh="문제해결",rs=["조건의 식 번역","치환·보조함수 도입"],st=["S05"],
 sol=r"$\left(\frac15\right)^{k-3}=k\Rightarrow k\cdot5^k=5^3$, 따라서 $\frac1{k^3 5^{3k}}=\frac1{5^9}$. $x<k$에서 $f$ 감소 확인 후, $f(\alpha)=\left(\frac15\right)^{\alpha-3}=\frac1{5^9}$인 $\alpha=12>k$. $f\left(\frac1{5^9}\right)=f(f(12))=36$"),
]
