R=[
dict(no=32,q=r"닫힌구간 $[0,12]$에서 정의된 두 함수 $f(x)=\cos\dfrac{\pi x}6$, $g(x)=-3\cos\dfrac{\pi x}6-1$이 있다. 곡선 $y=f(x)$와 직선 $y=k$가 만나는 두 점의 $x$좌표를 $\alpha_1,\alpha_2$라 할 때, $|\alpha_1-\alpha_2|=8$이다. 곡선 $y=g(x)$와 직선 $y=k$가 만나는 두 점의 $x$좌표를 $\beta_1,\beta_2$라 할 때, $|\beta_1-\beta_2|$의 값은? (단, $k$는 $-1<k<1$인 상수이다.)",
 cond=None,ch=["3",r"\frac72","4",r"\frac92","5"],ans="3",fig=None,th="09",lk=["10"],
 fj=r"주기 $12$, 대칭축 $x=6$이므로 $\alpha_1+\alpha_2=12$와 차 $8$로 교점을 바로 구한다.",
 bh="계산",rs=["대칭성·주기성 활용"],st=["S06"],
 sol=r"$\alpha_1+\alpha_2=12$, $\alpha_2-\alpha_1=8$ → $\alpha_1=2$, $k=\cos\frac\pi3=\frac12$. $-3\cos\frac{\pi x}6-1=\frac12\Rightarrow\cos\frac{\pi x}6=-\frac12$ → $x=4,8$. $|\beta_1-\beta_2|=4$"),
dict(no=33,q=r"닫힌구간 $[0,2\pi]$에서 정의된 함수 $f(x)=\begin{cases}\sin x-1 & (0\le x<\pi)\\ -\sqrt2\sin x-1 & (\pi\le x\le2\pi)\end{cases}$가 있다. $0\le t\le2\pi$인 실수 $t$에 대하여 $x$에 대한 방정식 $f(x)=f(t)$의 서로 다른 실근의 개수가 $3$이 되도록 하는 모든 $t$의 값의 합은 $\dfrac qp\pi$이다. $p+q$의 값을 구하시오. (단, $p$와 $q$는 서로소인 자연수이다.)",
 cond=None,ch=None,ans="15",fig=None,th="10",lk=["09"],
 fj=r"$f$의 그래프를 그리고 수평선 $y=f(t)$와 교점이 3개가 되는 높이($-1$, $0$)를 먼저 찾은 뒤 그 높이를 주는 $t$를 모두 모은다.",
 bh="추론",rs=["그래프·도형 해석","경우 나누기"],st=["S06"],
 sol=r"$[0,\pi)$: 최댓값 0, 최솟값 $-1$. $[\pi,2\pi]$: 최댓값 $\sqrt2-1$, 최솟값 $-1$. 교점 3개 ⇔ $f(t)=-1$ 또는 $0$. (i) $f(t)=-1$: $t=0,\pi,2\pi$. (ii) $f(t)=0$: $t=\frac\pi2$, $-\sqrt2\sin t-1=0$에서 $t=\frac54\pi,\frac74\pi$. 합 $\frac{13}2\pi$, $p+q=15$"),
dict(no=34,q=r"$-1\le t\le1$인 실수 $t$에 대하여 $x$에 대한 방정식 $\left(\sin\dfrac{\pi x}2-t\right)\left(\cos\dfrac{\pi x}2-t\right)=0$의 실근 중에서 집합 $\{x\mid0\le x<4\}$에 속하는 가장 작은 값을 $\alpha(t)$, 가장 큰 값을 $\beta(t)$라 하자. <보기>에서 옳은 것만을 있는 대로 고른 것은?",
 cond=r"ㄱ. $-1\le t<0$인 모든 실수 $t$에 대하여 $\alpha(t)+\beta(t)=5$이다.\\ㄴ. $\{t\mid\beta(t)-\alpha(t)=\beta(0)-\alpha(0)\}=\left\{t\,\middle|\,0\le t\le\dfrac{\sqrt2}2\right\}$\\ㄷ. $\alpha(t_1)=\alpha(t_2)$인 두 실수 $t_1,t_2$에 대하여 $t_2-t_1=\dfrac12$이면 $t_1t_2=\dfrac13$이다.",
 ch=["ㄱ","ㄱ, ㄴ","ㄱ, ㄷ","ㄴ, ㄷ","ㄱ, ㄴ, ㄷ"],ans="2",fig=None,th="10",lk=["09","11"],
 fj=r"$y=\sin\frac{\pi x}2$, $y=\cos\frac{\pi x}2$ 두 그래프와 수평선 $y=t$의 교점으로 보고, 대칭축 $x=1,3$과 대칭점 $(2,0)$을 활용한다.",
 bh="추론",rs=["대칭성·주기성 활용","경우 나누기","그래프·도형 해석"],st=["S06"],
 sol=r"ㄱ: $-1\le t<0$이면 $\alpha=1+k$, $\beta=4-k$ → 합 5 (참). ㄴ: $\beta(0)-\alpha(0)=3$; $0\le t\le\frac{\sqrt2}2$에서 $\beta-\alpha=3$, $\frac{\sqrt2}2<t<1$에서 $4-2k$, $t=1$에서 1, $t<0$에서 $<3$ (참). ㄷ: $\alpha(t_1)=\alpha(t_2)=\alpha$면 $t_1=\sin\frac\pi2\alpha$, $t_2=\cos\frac\pi2\alpha$, $t_2=t_1+\frac12$ → $\sin\frac\pi2\alpha=\frac{-1+\sqrt7}4$, $t_1t_2=\frac38$ (거짓). 답 ㄱ, ㄴ"),
dict(no=35,q=r"양수 $a$와 자연수 $b$에 대하여 $0\le x\le2$일 때 $x$에 대한 방정식 $\left\{\cos(b\pi x)-\dfrac12\right\}\left\{a\cos(b\pi x)+\dfrac{a+2}2\right\}=0$의 서로 다른 실근의 개수는 $15$이다. $a+b$의 값은?",
 cond=None,ch=["6",r"\frac{13}2","7",r"\frac{15}2","8"],ans="3",fig=None,th="10",lk=["09"],
 fj=r"두 번째 인수를 $\cos(b\pi x)=-\left(\frac12+\frac1a\right)$로 바꾸고, 이 값이 $-1$보다 작은지·같은지·큰지($a$와 $2$ 비교)로 나눈다.",
 bh="추론",rs=["경우 나누기","대칭성·주기성 활용"],st=["S06"],
 sol=r"한 주기 $\left[0,\frac2b\right]$에서 근의 수: (i) $a>2$: 4개 → $4b=15$ 불가. (ii) $a=2$: 3개 → $3b=15$, $b=5$. (iii) $0<a<2$: 2개 → $2b=15$ 불가. $a+b=7$"),
dict(no=36,q=r"$0\le x\le2\pi$일 때, 부등식 $\cos x\le\sin\dfrac\pi7$을 만족시키는 모든 $x$의 값의 범위는 $\alpha\le x\le\beta$이다. $\beta-\alpha$의 값은?",
 cond=None,ch=[r"\frac87\pi",r"\frac{17}{14}\pi",r"\frac97\pi",r"\frac{19}{14}\pi",r"\frac{10}7\pi"],ans="3",fig=None,th="10",lk=["11"],
 fj=r"$\sin\frac\pi7=\cos\frac{5\pi}{14}$로 바꿔 코사인끼리 비교한다.",
 bh="계산",rs=["대칭성·주기성 활용"],st=["S06"],
 sol=r"$\sin\frac\pi7=\cos\frac{5}{14}\pi$. $x_1=\frac5{14}\pi$, $x_2=2\pi-x_1=\frac{23}{14}\pi$. $\beta-\alpha=\frac97\pi$"),
dict(no=37,q=r"그림과 같이 $\overline{\mathrm{AB}}=3$, $\overline{\mathrm{BC}}=2$, $\overline{\mathrm{AC}}>3$이고 $\cos(\angle\mathrm{BAC})=\dfrac78$인 삼각형 $\mathrm{ABC}$가 있다. 선분 $\mathrm{AC}$의 중점을 $\mathrm{M}$, 삼각형 $\mathrm{ABC}$의 외접원이 직선 $\mathrm{BM}$과 만나는 점 중 $\mathrm{B}$가 아닌 점을 $\mathrm{D}$라 할 때, 선분 $\mathrm{MD}$의 길이는?",
 cond=None,ch=[r"\frac{3\sqrt{10}}5",r"\frac{7\sqrt{10}}{10}",r"\frac{4\sqrt{10}}5",r"\frac{9\sqrt{10}}{10}",r"\sqrt{10}"],ans="3",fig="삼각형 ABC의 외접원, AC의 중점 M, 직선 BM이 원과 다시 만나는 점 D",
 th="12",lk=[],
 fj=r"코사인법칙으로 $\overline{\mathrm{AC}}$를 구한 뒤, 원의 할선 성질(닮음) $\overline{\mathrm{MA}}\cdot\overline{\mathrm{MC}}=\overline{\mathrm{MB}}\cdot\overline{\mathrm{MD}}$를 쓴다.",
 bh="계산",rs=["그래프·도형 해석"],st=["S07","S08"],
 sol=r"$4=9+a^2-\frac{21}4a$ → $(4a-5)(a-4)=0$, $a=4$. $\overline{\mathrm{MB}}^2=9+4-2\cdot3\cdot2\cdot\frac78=\frac52$, $\overline{\mathrm{MB}}=\frac{\sqrt{10}}2$. $2\cdot2=\frac{\sqrt{10}}2\overline{\mathrm{MD}}$ → $\overline{\mathrm{MD}}=\frac{4\sqrt{10}}5$"),
dict(no=38,q=r"그림과 같이 $\overline{\mathrm{AB}}=4$, $\overline{\mathrm{AC}}=5$이고 $\cos(\angle\mathrm{BAC})=\dfrac18$인 삼각형 $\mathrm{ABC}$가 있다. 선분 $\mathrm{AC}$ 위의 점 $\mathrm{D}$와 선분 $\mathrm{BC}$ 위의 점 $\mathrm{E}$에 대하여 $\angle\mathrm{BAC}=\angle\mathrm{BDA}=\angle\mathrm{BED}$일 때, 선분 $\mathrm{DE}$의 길이는?",
 cond=None,ch=[r"\frac73",r"\frac52",r"\frac83",r"\frac{17}6","3"],ans="3",fig="삼각형 ABC와 AC 위의 D, BC 위의 E; $\angle$BAC$=\angle$BDA$=\angle$BED 표시",
 th="12",lk=[],
 fj=r"같은 각 조건에서 이등변삼각형($\overline{\mathrm{BD}}=\overline{\mathrm{AB}}=4$, $\overline{\mathrm{DB}}=\overline{\mathrm{DC}}$)을 찾아 길이를 확정한다.",
 bh="추론",rs=["그래프·도형 해석"],st=["S07"],
 sol=r"$\triangle\mathrm{ABD}$ 이등변 → $\overline{\mathrm{BD}}=4$, $\overline{\mathrm{AD}}=2\cdot4\cdot\frac18=1$, $\overline{\mathrm{DC}}=4$. $\overline{\mathrm{BC}}^2=16+25-5=36$, $\overline{\mathrm{BC}}=6$, $\overline{\mathrm{BH'}}=3$. $\overline{\mathrm{DE}}=x$면 $\overline{\mathrm{DH'}}=\frac{\sqrt{63}}8x$. $16=\frac{63}{64}x^2+9$ → $x=\frac83$"),
dict(no=39,q=r"두 점 $\mathrm{O}_1$, $\mathrm{O}_2$를 각각 중심으로 하고 반지름의 길이가 $\overline{\mathrm{O}_1\mathrm{O}_2}$인 두 원 $C_1$, $C_2$가 있다. 그림과 같이 원 $C_1$ 위의 서로 다른 세 점 $\mathrm{A,B,C}$와 원 $C_2$ 위의 점 $\mathrm{D}$가 주어져 있고, 세 점 $\mathrm{A},\mathrm{O}_1,\mathrm{O}_2$와 세 점 $\mathrm{C},\mathrm{O}_2,\mathrm{D}$가 각각 한 직선 위에 있다. 이때 $\angle\mathrm{BO}_1\mathrm{A}=\theta_1$, $\angle\mathrm{O}_2\mathrm{O}_1\mathrm{C}=\theta_2$, $\angle\mathrm{O}_1\mathrm{O}_2\mathrm{D}=\theta_3$이라 하자. 다음은 $\overline{\mathrm{AB}}:\overline{\mathrm{O}_1\mathrm{D}}=1:2\sqrt2$이고 $\theta_3=\theta_1+\theta_2$일 때, 선분 $\mathrm{AB}$와 선분 $\mathrm{CD}$의 길이의 비를 구하는 과정이다. 위의 (가), (다)에 알맞은 식을 각각 $f(k)$, $g(k)$라 하고, (나)에 알맞은 수를 $p$라 할 때, $f(p)\times g(p)$의 값은?",
 cond=r"$\angle\mathrm{CO}_2\mathrm{O}_1+\angle\mathrm{O}_1\mathrm{O}_2\mathrm{D}=\pi$이므로 $\theta_3=\dfrac\pi2+\dfrac{\theta_2}2$이고 $\theta_3=\theta_1+\theta_2$에서 $2\theta_1+\theta_2=\pi$이므로 $\angle\mathrm{CO}_1\mathrm{B}=\theta_1$. 이때 $\angle\mathrm{O}_2\mathrm{O}_1\mathrm{B}=\theta_1+\theta_2=\theta_3$이므로 삼각형 $\mathrm{O}_1\mathrm{O}_2\mathrm{B}$와 삼각형 $\mathrm{O}_2\mathrm{O}_1\mathrm{D}$는 합동이다. $\overline{\mathrm{AB}}=k$라 할 때, $\overline{\mathrm{BO}_2}=\overline{\mathrm{O}_1\mathrm{D}}=2\sqrt2k$이므로 $\overline{\mathrm{AO}_2}=$ (가) 이고, $\angle\mathrm{BO}_2\mathrm{A}=\dfrac{\theta_1}2$이므로 $\cos\dfrac{\theta_1}2=$ (나) 이다. 삼각형 $\mathrm{O}_2\mathrm{BC}$에서 $\overline{\mathrm{BC}}=k$, $\overline{\mathrm{BO}_2}=2\sqrt2k$, $\angle\mathrm{CO}_2\mathrm{B}=\dfrac{\theta_1}2$이므로 코사인법칙에 의하여 $\overline{\mathrm{O}_2\mathrm{C}}=$ (다) 이다. $\overline{\mathrm{CD}}=\overline{\mathrm{O}_2\mathrm{D}}+\overline{\mathrm{O}_2\mathrm{C}}=\overline{\mathrm{O}_1\mathrm{O}_2}+\overline{\mathrm{O}_2\mathrm{C}}$이므로 $\overline{\mathrm{AB}}:\overline{\mathrm{CD}}=k:\left(\dfrac{(가)}2+(다)\right)$이다.",
 ch=[r"\frac{169}{27}",r"\frac{56}9",r"\frac{167}{27}",r"\frac{166}{27}",r"\frac{55}9"],ans="2",fig="두 원 $C_1$, $C_2$(중심 $\mathrm O_1$, $\mathrm O_2$)와 점 A, B, C, D, 각 $\theta_1,\theta_2,\theta_3$",
 th="12",lk=[],
 fj=r"$\mathrm{AO_2}$가 지름이므로 $\angle\mathrm{ABO_2}=90^\circ$를 이용해 피타고라스로 (가)를 구하고, 이어서 과정을 따라간다.",
 bh="이해",rs=["그래프·도형 해석"],st=["S07","S08"],
 sol=r"(가) $\overline{\mathrm{AO_2}}=\sqrt{k^2+8k^2}=3k$. (나) $\cos\frac{\theta_1}2=\frac{2\sqrt2k}{3k}=\frac{2\sqrt2}3$. (다) $k^2=x^2+8k^2-2x\cdot2\sqrt2k\cdot\frac{2\sqrt2}3$ → $(3x-7k)(x-3k)=0$, $x=\frac73k$. $f(p)g(p)=3p\cdot\frac73p=7p^2=\frac{56}9$"),
]
