R=[
dict(no=14,q=r"$n\ge2$인 자연수 $n$에 대하여 두 곡선 $y=\log_n x$, $y=-\log_n(x+3)+1$이 만나는 점의 $x$좌표가 $1$보다 크고 $2$보다 작도록 하는 모든 $n$의 값의 합은?",
 cond=None,ch=["30","35","40","45","50"],ans="2",fig=None,th="04",lk=["05"],
 fj=r"교점 조건을 $\log_n x=\log_n\frac{n}{x+3}$으로 바꾸면 이차방정식 $x^2+3x-n=0$의 근이 $(1,2)$에 있을 조건이 된다.",
 bh="추론",rs=["조건의 식 번역"],st=["S03"],
 sol=r"$x=\frac{n}{x+3}\Rightarrow x^2+3x-n=0$. $f(x)=x^2+3x-n$에서 $f(1)=4-n<0$, $f(2)=10-n>0$ → $4<n<10$, $n=5,\dots,9$. 합 $35$"),
dict(no=15,q=r"실수 $a$ $(a>1)$에 대하여 곡선 $y=\log_a(x+3)$이 곡선 $y=\log_a(-x+3)$과 만나는 점을 $\mathrm{A}$, 곡선 $y=\log_a(x+3)$이 $x$축과 만나는 점을 $\mathrm{B}$, 곡선 $y=\log_a(-x+3)$이 $x$축과 만나는 점을 $\mathrm{C}$라 하자. 삼각형 $\mathrm{ABC}$가 정삼각형일 때, $a$의 값은?",
 cond=None,ch=[r"3^{\frac{\sqrt3}{6}}",r"3^{\frac{\sqrt3}{4}}",r"3^{\frac{\sqrt3}{3}}",r"3^{\frac{5\sqrt3}{12}}",r"3^{\frac{\sqrt3}{2}}"],ans="1",fig=None,th="04",lk=["06"],
 fj=r"두 곡선은 $y$축 대칭이므로 $\mathrm A$는 $y$축 위의 $(0,\log_a3)$이고, 정삼각형 조건은 $\tan\frac\pi3=\frac{\overline{\mathrm{OA}}}{\overline{\mathrm{OB}}}$이다.",
 bh="계산",rs=["대칭성·주기성 활용","그래프·도형 해석"],st=["S05"],
 sol=r"$\mathrm A(0,\log_a3)$, $\mathrm B(-2,0)$, $\mathrm C(2,0)$. $\sqrt3=\frac{\log_a3}{2}\Rightarrow a^{2\sqrt3}=3$, $a=3^{\frac{\sqrt3}{6}}$"),
dict(no=16,q=r"다음 그림과 같이 $1$보다 큰 실수 $b$에 대하여 두 함수 $f(x)=b^x$과 $g(x)=-\log_b x$의 그래프가 제1사분면에서 만나는 점 $\mathrm{P}$의 좌표를 $(\alpha,\beta)$라 하자. 다음은 $\alpha\beta^3=1$일 때, 직선 $\mathrm{OP}$의 기울기 $m$에 대하여 $g(m)$의 값을 구하는 과정이다. (단, $\mathrm{O}$는 원점이다.) 위의 (가), (나), (다)에 알맞은 수를 각각 $p,q,r$이라 할 때, $(pqr)^2$의 값을 구하시오.",
 cond=r"제1사분면에 있는 점 $\mathrm P(\alpha,\beta)$는 두 곡선 $y=f(x)$, $y=g(x)$ 위의 점이므로 두 양수 $\alpha,\beta$가 $\beta=b^\alpha$, $\beta=-\log_b\alpha$를 만족시킨다. $\alpha\beta^3=1$이고 $\alpha=\log_b\beta$, $\beta=-\log_b\alpha$이므로 $3\alpha-\beta=3\log_b\beta+\log_b\alpha=\log_b(\alpha\beta^3)=0$이다. 따라서 $m=\dfrac\beta\alpha=$ (가) 이다. $\beta^4=m\alpha\beta^3=m$이므로 $\beta=$ (나) 이다. $b=\alpha^{-\frac1\beta}$이고 $\alpha=\dfrac\beta m$이므로 $g(m)=-\log_b m=\dfrac{\beta}{\log_m\alpha}=\dfrac{\beta}{-1+\log_m\beta}=$ (다) 이다.",
 ch=None,ans="48",fig="증가하는 곡선 $y=f(x)=b^x$와 감소하는 곡선 $y=g(x)=-\log_b x$가 제1사분면의 점 P에서 만나는 그림",
 th="04",lk=["03"],
 fj=r"빈칸 과정의 흐름을 따라 $\beta=3\alpha$를 먼저 얻고 $m=3$을 확정한 뒤 나머지를 대입한다.",
 bh="이해",rs=["조건의 식 번역"],st=["S05"],
 sol=r"$3\alpha-\beta=0$ → $m=3$ (가). $\beta^4=3$ → $\beta=3^{1/4}$ (나). $g(m)=\frac{3^{1/4}}{-1+\frac14}=-4\cdot3^{-3/4}$ (다). $(pqr)^2=(-4\cdot3^{1/2})^2=48$"),
dict(no=17,q=r"실수 $t$에 대하여 두 곡선 $y=t-\log_2 x$와 $y=2^{x-t}$이 만나는 점의 $x$좌표를 $f(t)$라 하자. <보기>의 각 명제에 대하여 다음 규칙에 따라 $A,B,C$의 값을 정할 때, $A+B+C$의 값을 구하시오. (단, $A+B+C\ne0$)",
 cond=r"· 명제 ㄱ이 참이면 $A=100$, 거짓이면 $A=0$이다.\\· 명제 ㄴ이 참이면 $B=10$, 거짓이면 $B=0$이다.\\· 명제 ㄷ이 참이면 $C=1$, 거짓이면 $C=0$이다.\\<보기>\\ㄱ. $f(1)=1$이고 $f(2)=2$이다.\\ㄴ. 실수 $t$의 값이 증가하면 $f(t)$의 값도 증가한다.\\ㄷ. 모든 양의 실수 $t$에 대하여 $f(t)\ge t$이다.",
 ch=None,ans="110",fig=None,th="04",lk=["07"],
 fj=r"두 곡선을 각각 기본 곡선의 $t$만큼 평행이동으로 보고, 감소·증가 함수의 교점이 $t$에 따라 어떻게 움직이는지 본다.",
 bh="추론",rs=["그래프·도형 해석","단순화·특수화로 규칙성 찾기"],st=["S05"],
 sol=r"ㄱ: $t=1$일 때 두 곡선 모두 $(1,1)$, $t=2$일 때 모두 $(2,1)$ 지남 → 참. ㄴ: 두 곡선 모두 $t$만큼 오른쪽/위로 이동하므로 교점의 $x$좌표 증가 → 참. ㄷ: $f(t)\ge t\iff t-\log_2t\ge2^{0}=1$, 즉 $t-1\ge\log_2 t$; $1<t<2$에서 $\log_2t>t-1$이므로 거짓. $A+B+C=110$"),
dict(no=18,q=r"곡선 $y=\log_2 x$ 위에 서로 다른 두 점 $\mathrm{A}$, $\mathrm{B}$가 있다. 점 $\mathrm{A}$에서 직선 $y=x$에 내린 수선의 발을 $\mathrm{P}$라 하고, 점 $\mathrm{B}$를 직선 $y=x$에 대하여 대칭이동한 점을 $\mathrm{Q}$라 할 때, 네 점 $\mathrm{A,B,P,Q}$가 다음 조건을 만족시킨다. 사각형 $\mathrm{APQB}$의 넓이가 $\dfrac qp$일 때, $p+q$의 값을 구하시오. (단, $p$와 $q$는 서로소인 자연수이다.)",
 cond=r"(가) (직선 $\mathrm{AP}$의 $y$절편)$-$(직선 $\mathrm{BQ}$의 $y$절편)$=\dfrac{13}{2}$\\(나) 직선 $\mathrm{AB}$의 기울기는 $\dfrac67$이다.",
 ch=None,ans="73",fig=None,th="04",lk=["06"],
 fj=r"$\mathrm{AP}$, $\mathrm{BQ}$ 모두 기울기 $-1$인 직선이므로 $y$절편을 $a+\log_2a$, $b+\log_2b$로 쓰고 (나)와 연립한다.",
 bh="문제해결",rs=["미지수 소거·연립","대칭성·주기성 활용"],st=["S05"],
 sol=r"$\mathrm A(a,\log_2a)$, $\mathrm B(b,\log_2b)$. (가) $(a-b)+(\log_2a-\log_2b)=\frac{13}2$, (나) $\log_2a-\log_2b=\frac67(a-b)$ → $a-b=\frac72$, $\frac ab=8$ → $b=\frac12$, $a=4$. $\mathrm P(3,3)$, $\mathrm Q(-1,\frac12)$. $\overline{\mathrm{AP}}=\sqrt2$, $\overline{\mathrm{BQ}}=\frac{3\sqrt2}2$, 높이 $\overline{\mathrm{PM}}=\frac{13\sqrt2}4$. 넓이 $\frac12\left(\sqrt2+\frac{3\sqrt2}{2}\right)\frac{13\sqrt2}{4}=\frac{65}8$, $p+q=73$"),
dict(no=19,q=r"곡선 $y=\log_{16}(8x+2)$ 위의 점 $\mathrm{A}(a,b)$와 곡선 $y=4^{x-1}-\dfrac12$ 위의 점 $\mathrm{B}$가 제1사분면에 있다. 점 $\mathrm{A}$를 직선 $y=x$에 대하여 대칭이동한 점이 직선 $\mathrm{OB}$ 위에 있고 선분 $\mathrm{AB}$의 중점의 좌표가 $\left(\dfrac{77}8,\dfrac{133}8\right)$일 때, $ab=\dfrac qp$이다. $p+q$의 값을 구하시오. (단, $\mathrm{O}$는 원점이고, $p$와 $q$는 서로소인 자연수이다.)",
 cond=None,ch=None,ans="457",fig=None,th="06",lk=["04","07"],
 fj=r"두 곡선 식을 $16^y=8x+2$, $4^x=4y+2$로 바꾸면 한쪽이 다른 쪽을 $x\to\frac x2$, $y\to\frac y2$ 대신 넣은 관계(닮음)임이 보인다.",
 bh="문제해결",rs=["대칭성·주기성 활용","미지수 소거·연립"],st=["S05"],
 sol=r"$16^b=8a+2$, $\mathrm B(c,d)$: $4^c=4d+2$. 두 식 관계로 $d=2a$, $c=2b$ (점 $(b,a)$가 직선 $\mathrm{OB}$ 위). 중점: $a+2b=\frac{77}4$, $2a+b=\frac{133}4$ → $a=\frac{63}4$, $b=\frac74$. $ab=\frac{441}{16}$, $p+q=457$"),
dict(no=20,q=r"양수 $a$에 대하여 $x\ge-1$에서 정의된 함수 $f(x)$는 $f(x)=\begin{cases}-x^2+6x & (-1\le x<6)\\ a\log_4(x-5) & (x\ge6)\end{cases}$이다. $t\ge0$인 실수 $t$에 대하여 닫힌구간 $[t-1,t+1]$에서의 $f(x)$의 최댓값을 $g(t)$라 하자. 구간 $[0,\infty)$에서 함수 $g(t)$의 최솟값이 $5$가 되도록 하는 양수 $a$의 최솟값을 구하시오.",
 cond=None,ch=None,ans="10",fig=None,th="04",lk=[],
 fj=r"$g(0)=5$이고 $f(5)=5$, $f(6)=0$이므로 $t=6$일 때 구간 $[5,7]$의 최댓값이 $5$ 이상이어야 한다 → $f(7)\ge5$.",
 bh="추론",rs=["그래프·도형 해석","경우 나누기"],st=["S05"],
 sol=r"$g(0)=f(1)=5$. $1\le t\le5$에서 $g(t)\ge5$. $t=6$일 때 $[5,7]$에서 최댓값 $\ge5$ → $f(7)=a\log_4 2=\frac a2\ge5$, $a\ge10$. 최솟값 $10$"),
]
