R=[
dict(no=48,q=r"그림과 같이 $\overline{\mathrm{AB}}=3$, $\overline{\mathrm{BC}}=\sqrt{13}$, $\overline{\mathrm{AD}}\times\overline{\mathrm{CD}}=9$, $\angle\mathrm{BAC}=\dfrac\pi3$인 사각형 $\mathrm{ABCD}$가 있다. 삼각형 $\mathrm{ABC}$의 넓이를 $S_1$, 삼각형 $\mathrm{ACD}$의 넓이를 $S_2$라 하고, 삼각형 $\mathrm{ACD}$의 외접원의 반지름의 길이를 $R$이라 하자. $S_2=\dfrac56S_1$일 때, $\dfrac{R}{\sin(\angle\mathrm{ADC})}$의 값은?",
 cond=None,ch=[r"\frac{54}{25}",r"\frac{117}{50}",r"\frac{63}{25}",r"\frac{27}{10}",r"\frac{72}{25}"],ans="1",fig="사각형 ABCD와 삼각형 ACD의 외접원, $\angle$BAC$=\frac\pi3$",
 th="12",lk=[],
 fj=r"삼각형 $\mathrm{ABC}$는 SSA 조건이지만 코사인법칙으로 $\overline{\mathrm{AC}}$가 결정되고, 넓이 조건으로 $\sin(\angle\mathrm{ADC})$가 나온다.",
 bh="계산",rs=["그래프·도형 해석"],st=["S07","S08"],
 sol=r"$13=9+a^2-3a$ → $a=4$. $S_1=3\sqrt3$. $S_2=\frac92\sin(\angle\mathrm{ADC})=\frac56\cdot3\sqrt3$ → $\sin=\frac{5\sqrt3}9$. $2R=\frac{4}{5\sqrt3/9}$, $R=\frac{6\sqrt3}5$. $\frac{R}{\sin}=\frac{54}{25}$"),
dict(no=49,q=r"다음 조건을 만족시키는 삼각형 $\mathrm{ABC}$의 외접원의 넓이가 $9\pi$일 때, 삼각형 $\mathrm{ABC}$의 넓이는?",
 cond=r"(가) $3\sin A=2\sin B$\\(나) $\cos B=\cos C$",
 ch=[r"\frac{32}9\sqrt2",r"\frac{40}9\sqrt2",r"\frac{16}3\sqrt2",r"\frac{56}9\sqrt2",r"\frac{64}9\sqrt2"],ans="5",fig=None,th="12",lk=[],
 fj=r"(가)는 사인법칙으로 변의 비 $3a=2b$, (나)는 $b=c$(이등변)로 바꾼다.",
 bh="계산",rs=["조건의 식 번역"],st=["S07"],
 sol=r"$R=3$. $b=\frac32a$, $b=c$ → $a=2k$, $b=c=3k$. $\cos A=\frac{9+9-4}{18}=\frac79$, $\sin A=\frac{4\sqrt2}9$. $a=6\sin A=\frac{8\sqrt2}3$, $b=c=4\sqrt2$. 넓이 $\frac12\cdot32\cdot\frac{4\sqrt2}9=\frac{64\sqrt2}9$"),
dict(no=50,q=r"그림과 같이 삼각형 $\mathrm{ABC}$에서 선분 $\mathrm{AB}$ 위에 $\overline{\mathrm{AD}}:\overline{\mathrm{DB}}=3:2$인 점 $\mathrm{D}$를 잡고, 점 $\mathrm{A}$를 중심으로 하고 점 $\mathrm{D}$를 지나는 원을 $O$, 원 $O$와 선분 $\mathrm{AC}$가 만나는 점을 $\mathrm{E}$라 하자. $\sin A:\sin C=8:5$이고, 삼각형 $\mathrm{ADE}$와 삼각형 $\mathrm{ABC}$의 넓이의 비가 $9:35$이다. 삼각형 $\mathrm{ABC}$의 외접원의 반지름의 길이가 $7$일 때, 원 $O$ 위의 점 $\mathrm{P}$에 대하여 삼각형 $\mathrm{PBC}$의 넓이의 최댓값은? (단, $\overline{\mathrm{AB}}<\overline{\mathrm{AC}}$)",
 cond=None,ch=[r"18+15\sqrt3",r"24+20\sqrt3",r"30+25\sqrt3",r"36+30\sqrt3",r"42+35\sqrt3"],ans="4",fig="삼각형 ABC, A 중심 원 O(반지름 AD), AC와 원의 교점 E",
 th="12",lk=[],
 fj=r"원 $O$의 반지름을 $r$로 두고 모든 변을 $r$로 표현한 뒤, 최댓값은 '$\mathrm{A}$에서 $\mathrm{BC}$까지 거리 $+\,r$'이 높이일 때다.",
 bh="문제해결",rs=["그래프·도형 해석","미지수 소거·연립"],st=["S07","S08"],
 sol=r"$\overline{\mathrm{AD}}=\overline{\mathrm{AE}}=r$, $\overline{\mathrm{AB}}=\frac53r$, $\overline{\mathrm{CE}}=x$. 넓이비 $\frac12r^2:\frac56r(r+x)=9:35$ → $x=\frac43r$, $\overline{\mathrm{AC}}=\frac73r$. $\overline{\mathrm{BC}}=\frac53r\cdot\frac85=\frac83r$. $\cos\theta=\frac{11}{14}$, $\sin\theta=\frac{5\sqrt3}{14}$ ($\theta=\angle\mathrm{ACB}$). $\frac{5r/3}{\sin\theta}=14$ → $r=3\sqrt3$. $\overline{\mathrm{AH}}=\frac73r\sin\theta=\frac{15}2$. 최댓값 $\frac12\cdot8\sqrt3\cdot\left(3\sqrt3+\frac{15}2\right)=36+30\sqrt3$"),
]
