R=[
dict(no=28,q=r"양수 $k$에 대하여 집합 $\left\{x\,\middle|\,0\le x<\dfrac{3k\pi}2,\ x\ne\dfrac{k\pi}2\right\}$에서 정의된 함수 $f(x)=\tan\dfrac xk$가 있다. 점 $\mathrm{P}(0,p)$ $(p>0)$을 지나며 $x$축에 평행한 직선이 함수 $y=f(x)$의 그래프와 만나는 두 점을 $\mathrm{A}$, $\mathrm{B}$ $(\overline{\mathrm{PA}}<\overline{\mathrm{PB}})$라 하고, 직선 $y=-p$가 함수 $y=f(x)$의 그래프와 만나는 점을 $\mathrm{C}$라 하자. $\overline{\mathrm{AB}}=3\overline{\mathrm{PA}}$이고 삼각형 $\mathrm{OCB}$의 넓이가 $\dfrac{5\pi}3$일 때, $k+p$의 값은? (단, $\mathrm{O}$는 원점이다.)",
 cond=None,ch=[r"\frac{4\sqrt3}3",r"\frac{13\sqrt3}9",r"\frac{14\sqrt3}9",r"\frac{5\sqrt3}3",r"\frac{16\sqrt3}9"],ans="3",fig="$y=\tan\frac xk$의 두 가지와 직선 $y=p$(P, A, B), $y=-p$(C); 삼각형 OCB 색칠",
 th="09",lk=[],
 fj=r"주기 $k\pi$이므로 $\overline{\mathrm{AB}}=k\pi$, $\overline{\mathrm{PA}}=\frac{k\pi}3$을 바로 얻고, $\mathrm B$와 $\mathrm C$는 $x$축 위의 점 $\mathrm D(k\pi,0)$에 대해 대칭이다.",
 bh="추론",rs=["대칭성·주기성 활용","그래프·도형 해석"],st=["S06"],
 sol=r"$\overline{\mathrm{AB}}=\overline{\mathrm{OD}}=k\pi$, $\overline{\mathrm{PA}}=\frac{k\pi}3$. $p=\tan\frac\pi3=\sqrt3$. 넓이 $=\triangle\mathrm{ODB}+\triangle\mathrm{OCD}=\sqrt3k\pi=\frac{5\pi}3$ → $k=\frac{5\sqrt3}9$. $k+p=\frac{14\sqrt3}9$"),
dict(no=29,q=r"양수 $a$에 대하여 집합 $\left\{x\,\middle|\,-\dfrac a2<x\le a,\ x\ne\dfrac a2\right\}$에서 정의된 함수 $f(x)=\tan\dfrac{\pi x}a$가 있다. 그림과 같이 함수 $y=f(x)$의 그래프 위의 세 점 $\mathrm{O}$, $\mathrm{A}$, $\mathrm{B}$를 지나는 직선이 있다. 점 $\mathrm{A}$를 지나고 $x$축에 평행한 직선이 함수 $y=f(x)$의 그래프와 만나는 점 중 $\mathrm{A}$가 아닌 점을 $\mathrm{C}$라 하자. 삼각형 $\mathrm{ABC}$가 정삼각형일 때, 삼각형 $\mathrm{ABC}$의 넓이는? (단, $\mathrm{O}$는 원점이다.)",
 cond=None,ch=[r"\frac{3\sqrt3}2",r"\frac{17\sqrt3}{12}",r"\frac{4\sqrt3}3",r"\frac{5\sqrt3}4",r"\frac{7\sqrt3}6"],ans="3",fig="$y=\tan\frac{\pi x}a$ 그래프 위 원점을 지나는 직선 위의 A(제3사분면), B(제1사분면); A에서 수평선이 다음 가지와 만나는 점 C; 정삼각형 ABC",
 th="09",lk=[],
 fj=r"정삼각형이면 직선 $\mathrm{AB}$의 기울기가 $\sqrt3$이고, $\overline{\mathrm{AC}}$는 주기 $a$와 같다.",
 bh="추론",rs=["대칭성·주기성 활용","그래프·도형 해석"],st=["S06"],
 sol=r"$\mathrm B(t,\sqrt3t)$, $\mathrm A(-t,-\sqrt3t)$, $\overline{\mathrm{AB}}=4t=\overline{\mathrm{AC}}=a$. $\mathrm C(3t,-\sqrt3t)$가 곡선 위: $-\sqrt3t=\tan\frac{3\pi}4$ → $t=\frac1{\sqrt3}$. 넓이 $\frac{\sqrt3}4(4t)^2=\frac{4\sqrt3}3$"),
dict(no=30,q=r"함수 $f(x)=a-\sqrt3\tan2x$가 닫힌구간 $\left[-\dfrac\pi6,b\right]$에서 최댓값 $7$, 최솟값 $3$을 가질 때, $ab$의 값은? (단, $a,b$는 상수이다.)",
 cond=None,ch=[r"\frac\pi2",r"\frac{5\pi}{12}",r"\frac\pi3",r"\frac\pi4",r"\frac\pi6"],ans="3",fig=None,th="09",lk=[],
 fj=r"$f$는 구간에서 감소하므로 양 끝값이 최댓값·최솟값이다(단, 구간이 점근선을 넘지 않아야 함).",
 bh="계산",rs=["그래프·도형 해석"],st=["S06"],
 sol=r"$-\frac\pi6<b<\frac\pi4$. $f\left(-\frac\pi6\right)=a+3=7\Rightarrow a=4$. $f(b)=4-\sqrt3\tan2b=3\Rightarrow\tan2b=\frac{\sqrt3}3$, $b=\frac\pi{12}$. $ab=\frac\pi3$"),
dict(no=31,q=r"닫힌구간 $[0,2\pi]$에서 정의된 함수 $f(x)=a\cos bx+3$이 $x=\dfrac\pi3$에서 최댓값 $13$을 갖도록 하는 두 자연수 $a,b$의 순서쌍 $(a,b)$에 대하여 $a+b$의 최솟값은?",
 cond=None,ch=["12","14","16","18","20"],ans="3",fig=None,th="09",lk=[],
 fj=r"$a>0$이므로 최댓값은 $a+3$이고, $x=\frac\pi3$이 주기 $\frac{2\pi}b$의 정수배여야 한다.",
 bh="계산",rs=["대칭성·주기성 활용","정수 조건으로 후보 좁히기"],st=["S06"],
 sol=r"$a+3=13\Rightarrow a=10$. $\frac{2\pi}b\cdot n=\frac\pi3\Rightarrow b=6n$, 최소 $b=6$. $a+b=16$"),
]
