R=[
dict(no=40,q=r"$\overline{\mathrm{AB}}=2\sqrt7$인 삼각형 $\mathrm{ABC}$에서 선분 $\mathrm{BC}$의 중점을 $\mathrm{P}$, 선분 $\mathrm{BC}$를 $5:1$로 내분하는 점을 $\mathrm{Q}$라 하자. $\overline{\mathrm{AQ}}=3\sqrt2$, $\sin(\angle\mathrm{QAP}):\sin(\angle\mathrm{APQ})=\sqrt2:3$일 때, 삼각형 $\mathrm{ABC}$의 외접원의 넓이는?",
 cond=None,ch=[r"\frac{85}9\pi",r"\frac{88}9\pi",r"\frac{91}9\pi",r"\frac{94}9\pi",r"\frac{97}9\pi"],ans="2",fig="삼각형 ABC와 BC 위의 점 P(중점), Q(5:1 내분점)",
 th="12",lk=[],
 fj=r"삼각형 $\mathrm{APQ}$에서 사인법칙으로 $\overline{\mathrm{PQ}}$를 구하면 $\overline{\mathrm{BC}}$가 결정되고, 이후 삼각형이 SSS로 결정된다.",
 bh="추론",rs=["그래프·도형 해석","조건의 식 번역"],st=["S07"],
 sol=r"$\overline{\mathrm{PQ}}=\frac{\sqrt2}3\cdot3\sqrt2=2$. $\overline{\mathrm{BC}}=\frac12\overline{\mathrm{BC}}+2+\frac16\overline{\mathrm{BC}}$ → $\overline{\mathrm{BC}}=6$, $\overline{\mathrm{BQ}}=5$. $\cos B=\frac{28+25-18}{2\cdot2\sqrt7\cdot5}=\frac{\sqrt7}4$. $\overline{\mathrm{AC}}^2=28+36-2\cdot2\sqrt7\cdot6\cdot\frac{\sqrt7}4=22$. $\sin B=\frac34$, $R=\frac{\sqrt{22}}{2\cdot3/4}=\frac{2\sqrt{22}}3$. 넓이 $\frac{88}9\pi$"),
dict(no=41,q=r"그림과 같이 사각형 $\mathrm{ABCD}$가 한 원에 내접하고 $\overline{\mathrm{AB}}=5$, $\overline{\mathrm{AC}}=3\sqrt5$, $\overline{\mathrm{AD}}=7$, $\angle\mathrm{BAC}=\angle\mathrm{CAD}$일 때, 이 원의 반지름의 길이는?",
 cond=None,ch=[r"\frac{5\sqrt2}2",r"\frac{8\sqrt5}5",r"\frac{5\sqrt5}3",r"\frac{8\sqrt2}3",r"\frac{9\sqrt3}4"],ans="1",fig="원에 내접하는 사각형 ABCD, 대각선 AC, $\angle$BAC$=\angle$CAD 표시",
 th="12",lk=[],
 fj=r"같은 원주각에 대한 현이므로 $\overline{\mathrm{BC}}=\overline{\mathrm{CD}}$; 두 삼각형에서 코사인법칙을 세워 $\cos\theta$를 구한다.",
 bh="추론",rs=["그래프·도형 해석","미지수 소거·연립"],st=["S07","S08"],
 sol=r"$\overline{\mathrm{BC}}^2=70-30\sqrt5\cos\theta$, $\overline{\mathrm{CD}}^2=94-42\sqrt5\cos\theta$, 같으므로 $\cos\theta=\frac{2\sqrt5}5$, $\overline{\mathrm{BC}}=\sqrt{10}$, $\sin\theta=\frac{\sqrt5}5$. $2R=\frac{\sqrt{10}}{\sqrt5/5}=5\sqrt2$, $R=\frac{5\sqrt2}2$"),
dict(no=42,q=r"그림과 같이 $\overline{\mathrm{AB}}=3$, $\overline{\mathrm{BC}}=4$이고 $\angle\mathrm{B}=\dfrac\pi2$인 직각삼각형 $\mathrm{ABC}$가 있다. 선분 $\mathrm{AB}$를 $2:1$로 내분하는 점을 $\mathrm{D}$, 점 $\mathrm{A}$를 중심으로 하고 반지름의 길이가 $\overline{\mathrm{AD}}$인 원이 선분 $\mathrm{AC}$와 만나는 점을 $\mathrm{E}$, 직선 $\mathrm{AB}$가 이 원과 만나는 점 중 $\mathrm{D}$가 아닌 점을 $\mathrm{F}$라 하고, 호 $\mathrm{EF}$ 위의 점 $\mathrm{G}$를 $\overline{\mathrm{CG}}=2\sqrt6$이 되도록 잡는다. 세 점 $\mathrm{C,E,G}$를 지나는 원 위의 점 $\mathrm{H}$가 $\angle\mathrm{HCG}=\angle\mathrm{BAC}$를 만족시킬 때, 선분 $\mathrm{GH}$의 길이는?",
 cond=None,ch=[r"\frac{6\sqrt{15}}5",r"\frac{38\sqrt{10}}{25}",r"\frac{14\sqrt3}5",r"\frac{32\sqrt{15}}{25}",r"\frac{8\sqrt{10}}5"],ans="4",fig="직각삼각형 ABC, A 중심 반지름 2인 원(D, E, F, G), C·E·G·H를 지나는 원",
 th="12",lk=[],
 fj=r"$\overline{\mathrm{GH}}=2R\sin\angle\mathrm{HCG}$이므로 원 $\mathrm{CEG}$의 반지름 $R$을 삼각형 $\mathrm{CGE}$에서 구하는 것이 목표다.",
 bh="문제해결",rs=["그래프·도형 해석"],st=["S07","S08"],
 sol=r"$\overline{\mathrm{AC}}=5$, $\sin\theta_1=\frac45$. $\overline{\mathrm{AG}}=\overline{\mathrm{AE}}=2$, $\cos\angle\mathrm{CAG}=\frac{4+25-24}{20}=\frac14$, $\overline{\mathrm{GE}}^2=8-2=6$. $\cos\angle\mathrm{ECG}=\frac{24+9-6}{2\cdot2\sqrt6\cdot3}=\frac{3\sqrt6}8$, $\sin=\frac{\sqrt{10}}8$. $2R=\frac{\sqrt6}{\sqrt{10}/8}=\frac{8\sqrt{15}}5$. $\overline{\mathrm{GH}}=2R\sin\theta_1=\frac{32\sqrt{15}}{25}$"),
dict(no=43,q=r"그림과 같이 사각형 $\mathrm{ABCD}$가 한 원에 내접하고 $\overline{\mathrm{AB}}:\overline{\mathrm{CD}}=1:3$, $\overline{\mathrm{BC}}<\overline{\mathrm{AD}}$일 때, 직선 $\mathrm{AB}$와 직선 $\mathrm{CD}$가 만나는 점을 $\mathrm{P}$라 하자. 다음은 $\overline{\mathrm{PB}}:\overline{\mathrm{PC}}:\overline{\mathrm{BC}}=7:5:\sqrt{14}$이고 $\overline{\mathrm{AD}}=4\sqrt{13}$일 때, 삼각형 $\mathrm{BPC}$의 외접원의 반지름의 길이를 구하는 과정이다. 위의 (가), (나), (다)에 알맞은 수를 각각 $p,q,r$이라 할 때, $p+q+r$의 값을 구하시오.",
 cond=r"$\angle\mathrm{BPC}=\theta$라 할 때, $\overline{\mathrm{PB}}:\overline{\mathrm{PC}}:\overline{\mathrm{BC}}=7:5:\sqrt{14}$이므로 삼각형 $\mathrm{BPC}$에서 코사인법칙에 의하여 $\cos\theta=\dfrac67$이다. $\overline{\mathrm{PB}}=7k$, $\overline{\mathrm{PC}}=5k$, $\overline{\mathrm{AB}}=l$, $\overline{\mathrm{CD}}=3l$이라 하자. 원의 성질에 의하여 삼각형 $\mathrm{BPC}$와 삼각형 $\mathrm{DPA}$가 서로 닮음이므로 $\overline{\mathrm{PB}}:\overline{\mathrm{PC}}=\overline{\mathrm{PD}}:\overline{\mathrm{PA}}$이고, $l=$ (가) $\cdot k$이다. 삼각형 $\mathrm{BPC}$와 삼각형 $\mathrm{DPA}$의 닮음비가 $1:$ (나) 이므로 $\overline{\mathrm{BC}}=\dfrac1{(나)}\cdot\overline{\mathrm{AD}}$이다. 따라서 삼각형 $\mathrm{BPC}$의 외접원의 반지름의 길이를 $R$이라 할 때, 삼각형 $\mathrm{BPC}$에서 사인법칙에 의하여 $R=$ (다) 이다.",
 ch=None,ans="12",fig="원에 내접하는 사각형 ABCD와 직선 AB, CD의 교점 P",
 th="12",lk=[],
 fj=r"할선이 만드는 닮음 $\triangle\mathrm{BPC}\sim\triangle\mathrm{DPA}$로 비례식을 세워 $l$과 $k$의 관계를 얻는다.",
 bh="이해",rs=["그래프·도형 해석"],st=["S07","S08"],
 sol=r"$7:5=(5k+3l):(7k+l)$ → $l=3k$ (가). $\overline{\mathrm{PD}}=14k$, 닮음비 $7k:14k=1:2$ (나). $\sin\theta=\frac{\sqrt{13}}7$, $\overline{\mathrm{BC}}=2\sqrt{13}$, $R=\frac{2\sqrt{13}}{2\cdot\sqrt{13}/7}=7$ (다). $p+q+r=12$"),
]
