R=[
dict(no=51,q=r"그림과 같이 $\overline{\mathrm{BC}}=3$, $\overline{\mathrm{CD}}=2$, $\cos(\angle\mathrm{BCD})=-\dfrac13$, $\angle\mathrm{DAB}>\dfrac\pi2$인 사각형 $\mathrm{ABCD}$에서 두 삼각형 $\mathrm{ABC}$와 $\mathrm{ACD}$는 모두 예각삼각형이다. 선분 $\mathrm{AC}$를 $1:2$로 내분하는 점 $\mathrm{E}$에 대하여 선분 $\mathrm{AE}$를 지름으로 하는 원이 두 선분 $\mathrm{AB}$, $\mathrm{AD}$와 만나는 점 중 $\mathrm{A}$가 아닌 점을 각각 $\mathrm{P}_1$, $\mathrm{P}_2$라 하고, 선분 $\mathrm{CE}$를 지름으로 하는 원이 두 선분 $\mathrm{BC}$, $\mathrm{CD}$와 만나는 점 중 $\mathrm{C}$가 아닌 점을 각각 $\mathrm{Q}_1$, $\mathrm{Q}_2$라 하자. $\overline{\mathrm{P}_1\mathrm{P}_2}:\overline{\mathrm{Q}_1\mathrm{Q}_2}=3:5\sqrt2$이고 삼각형 $\mathrm{ABD}$의 넓이가 $2$일 때, $\overline{\mathrm{AB}}+\overline{\mathrm{AD}}$의 값은? (단, $\overline{\mathrm{AB}}>\overline{\mathrm{AD}}$)",
 cond=None,ch=[r"\sqrt{21}",r"\sqrt{22}",r"\sqrt{23}",r"2\sqrt6","5"],ans="1",fig="사각형 ABCD, 대각선 AC 위의 E, AE·CE를 지름으로 하는 두 원과 교점 $\mathrm P_1,\mathrm P_2,\mathrm Q_1,\mathrm Q_2$",
 th="12",lk=[],
 fj=r"두 원의 지름 비가 $1:2$이므로 반지름을 $r$, $2r$로 두고 사인법칙으로 $\sin\alpha:\sin\beta$를 얻는다($\alpha=\angle\mathrm{BCD}$, $\beta=\angle\mathrm{DAB}$).",
 bh="문제해결",rs=["그래프·도형 해석","미지수 소거·연립"],st=["S07","S08"],
 sol=r"$\overline{\mathrm{BD}}^2=9+4+4=17$. $\frac{\overline{\mathrm{P_1P_2}}}{\sin\beta}=2r$, $\frac{\overline{\mathrm{Q_1Q_2}}}{\sin\alpha}=4r$ → $\sin\beta=\frac{6\sin\alpha}{5\sqrt2}$; $\sin\alpha=\frac{2\sqrt2}3$ → $\sin\beta=\frac45$, $\cos\beta=-\frac35$. $\frac12ab\cdot\frac45=2$ → $ab=5$. $a^2+b^2+6=17$ → $a^2+b^2=11$. $(a+b)^2=21$"),
dict(no=52,q=r"$a_2=-4$이고 공차가 $0$이 아닌 등차수열 $\{a_n\}$에 대하여 수열 $\{b_n\}$을 $b_n=a_n+a_{n+1}$ $(n\ge1)$이라 하고, 두 집합 $A$, $B$를 $A=\{a_1,a_2,a_3,a_4,a_5\}$, $B=\{b_1,b_2,b_3,b_4,b_5\}$라 하자. $n(A\cap B)=3$이 되도록 하는 모든 수열 $\{a_n\}$에 대하여 $a_{20}$의 값의 합은?",
 cond=None,ch=["30","34","38","42","46"],ans="5",fig=None,th="13",lk=[],
 fj=r"$\{b_n\}$도 공차 $2d$인 등차수열이므로 공차 부호로 나누고, 두 수열의 항이 '몇 칸 어긋나 겹치는지'로 센다.",
 bh="추론",rs=["경우 나누기","조건의 식 번역"],st=["S09"],
 sol=r"(i) $d>0$: $a_1<0$, $b_1<a_1$; $n(A\cap B)=3$이려면 $b_2=a_1$ 또는 $b_3=a_1$. (a) $b_2=a_1$: $-8+d=-4-d$, $d=2$, $a_{20}=32$. (b) $b_3=a_1$: $-8+3d=-4-d$, $d=1$, $a_{20}=14$. (ii) $d<0$: 어떤 경우든 $n(A\cap B)\le2$. 합 $46$"),
dict(no=53,q=r"실수 전체의 집합에서 정의된 함수 $f(x)$가 다음 조건을 만족시킨다. 방정식 $f(f(x))=f(x)$의 $0$ 이상인 모든 실근을 작은 수부터 크기순으로 나열할 때, $n$번째 수를 $a_n$이라 하자. 다음은 $a_{20}+a_{21}+a_{22}$의 값을 구하는 과정이다. 위의 (가), (나), (다)에 알맞은 수를 각각 $p,q,r$이라 할 때, $p+q+r$의 값을 구하시오.",
 cond=r"[조건] $0\le x<4$일 때 $f(x)=-x^2+4x$이고, 모든 실수 $x$에 대하여 $f(x+4)=f(x)$이다.\\[과정] 방정식 $f(x)=x$의 모든 실근이 $0,3$이므로 방정식 $f(f(x))=f(x)$의 실근을 구하는 것은 방정식 $f(x)\{f(x)-3\}=0$의 실근을 구하는 것과 같다. $0\le x<4$일 때, 방정식 $f(x)\{f(x)-3\}=0$의 모든 실근은 $0$, (가), $3$이므로 $a_1=0$, $a_2=$ (가), $a_3=3$이다. 또한, 모든 실수 $x$에 대하여 $f(x+4)=f(x)$이므로 세 수열 $\{a_{3n-2}\}$, $\{a_{3n-1}\}$, $\{a_{3n}\}$은 첫째항이 각각 $0$, (가), $3$이고 공차가 모두 (나) 인 등차수열이다. 따라서 $a_{20}+a_{21}+a_{22}=$ (다) 이다.",
 ch=None,ans="85",fig=None,th="13",lk=[],
 nr=["원문 해설의 a_20+a_21+a_22 계산은 25+27+28=80으로 표기됨(정답 85는 p+q+r=1+4+80)"],
 fj=r"$f(X)=X$의 근 $X=0,3$을 먼저 구해 $f(x)=0$ 또는 $f(x)=3$으로 바꾸고, 주기 $4$로 근이 3개씩 반복됨을 본다.",
 bh="이해",rs=["치환·보조함수 도입","대칭성·주기성 활용"],st=["S09"],
 sol=r"$f(x)=x\Rightarrow x=0,3$. $0\le x<4$에서 $f(x)=0\Rightarrow x=0$, $f(x)=3\Rightarrow x=1,3$. (가) $1$, (나) $4$. $a_{20}=a_{3\cdot7-1}=1+24=25$, $a_{21}=3+24=27$, $a_{22}=a_{3\cdot8-2}=0+28=28$, (다) $80$. $p+q+r=85$"),
dict(no=54,q=r"공비가 양수인 등비수열 $\{a_n\}$이 $2a_1(a_1+a_3)=5a_2(a_1+a_2)=20$을 만족시킬 때, $a_1a_6$의 값은?",
 cond=None,ch=[r"\frac1{27}",r"\frac19",r"\frac13","1","3"],ans="1",fig=None,th="13",lk=[],
 fj=r"첫째항 $a$, 공비 $r$로 두면 앞의 등식에서 $a^2$이 약분되어 $r$에 대한 이차방정식이 된다.",
 bh="계산",rs=["미지수 소거·연립"],st=["S09"],
 sol=r"$2a^2(1+r^2)=5a^2r(1+r)$ → $3r^2+5r-2=0$, $r=\frac13$. $2a^2(1+r^2)=20$ → $a^2=9$. $a_1a_6=a^2r^5=\frac1{27}$"),
dict(no=55,q=r"등비수열 $\{a_n\}$이 $2(a_1+a_4+a_7)=a_4+a_7+a_{10}=6$을 만족시킬 때, $a_{10}$의 값은?",
 cond=None,ch=[r"\frac{22}7",r"\frac{24}7",r"\frac{26}7",r"\frac{30}7",r"\frac{32}7"],ans="2",fig=None,th="13",lk=[],
 fj=r"$a_4+a_7+a_{10}=r^3(a_1+a_4+a_7)$이므로 두 식을 나누면 $r^3$이 바로 나온다.",
 bh="계산",rs=["미지수 소거·연립"],st=["S09"],
 sol=r"$a_1(1+r^3+r^6)=3$, $a_1r^3(1+r^3+r^6)=6$ → $r^3=2$, $a_1=\frac37$. $a_{10}=a_1r^9=\frac{24}7$"),
]
